$("#one").fadeToggle("slow",function(){
		$("#first_line").fadeToggle("slow",function(){
		$(this).animate({height:"50px",width:"5px"});
			$("#second_line").fadeToggle("slow",function(){
				$(this).animate({height:"5px",width:"70px"});
				$("#two").fadeToggle("slow",function(){
					$("#third_line").fadeToggle("slow",function(){
						$(this).animate({height:"50px",width:"5px"});
						$("#fourth_line").fadeToggle("slow",function(){
							$(this).animate({height:"5px",width:"60px"});
							$("#three").fadeToggle("slow",function(){
								$("#fifth_line").fadeToggle("slow",function(){
									$(this).animate({height:"130px",width:"5px"});
									$("#sixth_line").fadeToggle("slow",function(){
										$(this).animate({height:"6px",width:"60px"});
										$("#four").fadeToggle("slow",function(){
											$("#seventh_line").fadeToggle("slow",function(){
												$("#five").fadeToggle("slow",function(){
													$("#eighth_line").fadeToggle("slow",function(){
														$("#ninth_line").fadeToggle("slow",function(){
															$("#tenth_line").fadeToggle("slow",function(){
																$("#six").fadeToggle("slow",function(){
																	$("#eleventh_line").fadeToggle("slow",function(){
																		$("#twelve_line").fadeToggle("slow",function(){
																			$("#seven").fadeToggle("slow",function(){
																				$("#thirteenth_line").fadeToggle("slow",function(){
																					$("#fourteenth_line").fadeToggle("slow",function(){
																						$("#fifteenth_line").fadeToggle("slow",function(){
																						});
																						$("#sixteenth_line").fadeToggle("slow",function(){
																						});
																						$("#seventeenth_line").fadeToggle("slow",function(){
																						});
																						$("#one_eight_line").fadeToggle("slow",function(){
																							$("#one_nine_line").fadeToggle("slow",function(){
																							});
																							$("#two_zero_line").fadeToggle("slow",function(){
																							});
																							$("#twenty_one").fadeToggle("slow",function(){
																							});
																							$("#twenty_two").fadeToggle("slow",function(){
																								$("#eight").fadeToggle("slow",function(){
																								});
																								$("#nine").fadeToggle("slow",function(){
																								});
																								$("#ten").fadeToggle("slow",function(){
																								});
																								$("#eleven").fadeToggle("slow",function(){
																								});
																								
																								
																							});
																						});
																					});
																				});
																			});
																	});
																});
															});
														});
													});
												});
											});
										});
									});
								});
							});
						});
					});
				});
			});
		});
	});
});